# Generated by Django 3.1.6 on 2021-02-12 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0004_auto_20210211_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recording',
            name='datetime',
            field=models.DateTimeField(),
        ),
    ]
