# Generated by Django 3.1.6 on 2021-02-12 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0005_auto_20210212_1213'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Camara',
            new_name='Camera',
        ),
    ]
