# Generated by Django 3.1.6 on 2021-02-17 19:13

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('person_name', models.CharField(max_length=50)),
                ('ticket_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('seatnum', models.PositiveIntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10000)])),
            ],
        ),
        migrations.CreateModel(
            name='VacatedSeats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vacated_seat', models.PositiveIntegerField()),
            ],
        ),
    ]
