# Generated by Django 3.1.6 on 2021-02-21 14:07

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('TheatreAPI', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('person_name', models.CharField(max_length=50)),
                ('ticket_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('seatnum', models.PositiveIntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
            ],
        ),
        migrations.RenameModel(
            old_name='VacatedSeats',
            new_name='Vacated_Seats',
        ),
        migrations.DeleteModel(
            name='Tickets',
        ),
    ]
