# Generated by Django 3.1.6 on 2021-02-21 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TheatreAPI', '0002_auto_20210221_1407'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='person_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='seatnum',
            new_name='seatno',
        ),
    ]
