# Generated by Django 3.1.6 on 2021-02-11 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='camara',
            name='active_hours',
            field=models.CharField(default='9AM TO 9PM', max_length=50),
        ),
        migrations.AddField(
            model_name='camara',
            name='name',
            field=models.CharField(default='undefined', max_length=50),
        ),
    ]
