# Generated by Django 3.1.6 on 2021-02-11 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0002_auto_20210211_0458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recording',
            name='datetime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
