# Generated by Django 3.1.6 on 2021-02-11 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0003_auto_20210211_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recording',
            name='path',
            field=models.CharField(max_length=150),
        ),
    ]
