# Generated by Django 3.1.6 on 2021-02-13 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0006_auto_20210212_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recording',
            name='datetime',
            field=models.CharField(max_length=50),
        ),
    ]
